name: backoffice
service:
  env:
    - name: OPENAI_API_KEY
      valueFrom:
        secretKeyRef:
          key: OPENAI_API_KEY
          name: api-key-secret
  image: samirachoscalac/akka-demo:backoffice-0.0.0-prod
  resources:
    runtime:
      mode: embedded