name: backoffice
service:
  env:
    - name: OPENAI_API_KEY
      valueFrom:
        secretKeyRef:
          key: OPENAI_API_KEY
          name: api-key-secret
  image: kcr.us-east-1.kalix.io/lightbend-eng/release-pipeline-test/backoffice:1.0-1.0.0-dev
  resources:
    runtime:
      mode: embedded
