env:
  - name: OPENAI_API_KEY
    valueFrom:
      secretKeyRef:
        key: OPENAI_API_KEY
        name: api-key-secret
image: kcr.us-east-1.kalix.io/lightbend-eng/release-pipeline-test/backoffice:latest
resources:
  runtime:
    mode: embedded
